main_path = "./dataset/reviews_filtered_20_5.csv"
lowercased_path = "./dataset/reviews_filtered_20_5_lowercased.csv"
nostopwords_path = "./dataset/reviews_filtered_20_5_lowercased_nostopwords.csv"
reviewers_stats_path = "./dataset/reviewers_stats.csv"
listings_stats_path = "./dataset/listings_stats.csv"

main_full_path = "./dataset/reviews_filtered_20.csv"
lowercased_full_path = "./dataset/reviews_filtered_20_lowercased.csv"
nostopwords_full_path = "./dataset/reviews_filtered_20_lowercased_nostopwords.csv"
reviewers_stats_full_path = "./dataset/reviewers_stats_20.csv"
listings_stats_full_path = "./dataset/listings_stats_20.csv"
